name: 'uk_food_hygiene'
version: '1.0.0'
config-version: 2

profile: 'uk_food_hygiene'

model-paths: ["models"]
test-paths: ["tests"]

models:
  uk_food_hygiene:

    staging:
      +schema: staging
      +materialized: view

    silver:
      +schema: silver
      +materialized: table

    gold:
      +schema: gold
      +materialized: table